# Generated by Django 3.1.4 on 2020-12-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
